(module
 (table 0 anyfunc)
 (memory $0 1)
 (data (i32.const 16) "hello, i am Wbubbler, your friend !\nbub is cool\nadd Wbubbler#7474 on discord.\ntell friends to install me i am funny\00")
 (export "memory" (memory $0))
 (export "_Z8wbubblerv" (func $_Z8wbubblerv))
 (func $_Z8wbubblerv (; 0 ;) (result i32)
  (i32.const 16)
 )
)
